# Generated by Django 4.2.17 on 2024-12-28 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'зал', 'verbose_name_plural': 'Залы'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='is_taken',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='session',
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название/номер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cinema.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.CreateModel(
            name='SeatForSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_taken', models.BooleanField(verbose_name='Занято')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.seat', verbose_name='Место')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'место на сеанс',
                'verbose_name_plural': 'Места на сеанс',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='seat',
            field=models.ManyToManyField(through='cinema.SeatForSession', to='cinema.seat'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_for_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.seatforsession', verbose_name='Место на сеанс'),
            preserve_default=False,
        ),
    ]
