# Generated by Django 4.2.17 on 2025-01-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0002_alter_genre_options_alter_hall_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movies', to='cinema.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='seatforsession',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.seat', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='seatforsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats_for_session', to='cinema.session', verbose_name='Сеанс'),
        ),
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.hall', verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_for_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.seatforsession', verbose_name='Место на сеанс'),
        ),
    ]
