# Generated by Django 4.2.17 on 2025-01-06 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_rename_seat_session_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats_quantity',
            field=models.IntegerField(help_text='Мест должно быть не менее 10', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Количество мест'),
        ),
    ]
