# Generated by Django 4.2.17 on 2025-01-06 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_hall_seats_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Продолжительность'),
        ),
    ]
