# Generated by Django 4.2.17 on 2025-01-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_in_the_cinema',
            field=models.BooleanField(default=True, verbose_name='В прокате'),
        ),
    ]
