# Generated by Django 4.2.17 on 2025-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('datetime',), 'verbose_name': 'сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Продан'),
        ),
    ]
